pool:
  vmImage: 'windows-2022'

trigger:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

pr: 
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

steps:
  - checkout: self
    clean: 'true'

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.10.3'

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml
    displayName: Use GitVersion

  # This SDK version is needed as long as `uap10.0` will be supported in Uno.Core
  - powershell: .\build\Install-WindowsSdkISO.ps1 17763
    displayName: Install Windows SDK 17763

  - task: MSBuild@1
    inputs:
      solution: src/Uno.Core.sln
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\vs2017" "/p:PackageVersion=$(GITVERSION.FullSemVer)" "/p:InformationalVersion=$(GITVERSION.InformationalVersion)" /detailedsummary /bl:$(Build.ArtifactStagingDirectory)/Uno.Core.binlog
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'binlog'
      publishLocation: 'Container'
    condition: always()

  - task: VisualStudioTestPlatformInstaller@1

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*test*.dll
        !**\obj\**
      vsTestVersion: toolsInstaller
      testSelector: testAssemblies

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.PackageDiff"
      SignPackageDescription: "Uno.PackageDiff"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: $(Build.DefinitionName)
